"""Add title and thumbnail_path to sessions

Revision ID: 4d527441f2be
Revises: cfccba0923e1
Create Date: 2026-02-20 10:06:01.846930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d527441f2be'
down_revision: Union[str, Sequence[str], None] = 'cfccba0923e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('sessions', sa.Column('thumbnail_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'thumbnail_path')
    op.drop_column('sessions', 'title')
    # ### end Alembic commands ###
