"""Add deliveries table

Revision ID: cfccba0923e1
Revises: bd05d8ef27be
Create Date: 2026-02-20 07:08:03.299470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfccba0923e1'
down_revision: Union[str, Sequence[str], None] = 'bd05d8ef27be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ball_tracking_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('delivery_number', sa.Integer(), nullable=True),
    sa.Column('trajectory_3d', sa.JSON(), nullable=True),
    sa.Column('release_point_3d', sa.JSON(), nullable=True),
    sa.Column('pitch_landing_3d', sa.JSON(), nullable=True),
    sa.Column('bat_contact_3d', sa.JSON(), nullable=True),
    sa.Column('final_position_3d', sa.JSON(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('spin_rpm', sa.Float(), nullable=True),
    sa.Column('swing_angle', sa.Float(), nullable=True),
    sa.Column('seam_angle', sa.Float(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('is_yorker', sa.Boolean(), nullable=True),
    sa.Column('is_bouncer', sa.Boolean(), nullable=True),
    sa.Column('is_full_toss', sa.Boolean(), nullable=True),
    sa.Column('shot_power', sa.Float(), nullable=True),
    sa.Column('shot_timing', sa.Float(), nullable=True),
    sa.Column('runs_scored', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ball_tracking_analyses_id'), 'ball_tracking_analyses', ['id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('delivery_number', sa.Integer(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('spin_rpm', sa.Float(), nullable=True),
    sa.Column('swing_angle', sa.Float(), nullable=True),
    sa.Column('pitch_landing_x', sa.Float(), nullable=True),
    sa.Column('pitch_landing_y', sa.Float(), nullable=True),
    sa.Column('line', sa.String(), nullable=True),
    sa.Column('length', sa.String(), nullable=True),
    sa.Column('is_boundary', sa.Boolean(), nullable=True),
    sa.Column('boundary_type', sa.String(), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('elbow_extension', sa.Float(), nullable=True),
    sa.Column('release_point_x', sa.Float(), nullable=True),
    sa.Column('release_point_y', sa.Float(), nullable=True),
    sa.Column('release_point_z', sa.Float(), nullable=True),
    sa.Column('shot_type', sa.String(), nullable=True),
    sa.Column('shot_power', sa.Float(), nullable=True),
    sa.Column('shot_timing', sa.Float(), nullable=True),
    sa.Column('shot_direction', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_id'), 'deliveries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliveries_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_ball_tracking_analyses_id'), table_name='ball_tracking_analyses')
    op.drop_table('ball_tracking_analyses')
    # ### end Alembic commands ###
