"""add_annotated_video_path_to_sessions

Revision ID: fd5196852fc3
Revises: 94e87ece3f35
Create Date: 2026-05-03 16:15:24.238540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5196852fc3'
down_revision: Union[str, Sequence[str], None] = '94e87ece3f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('bowling_arm', sa.String(length=50), nullable=True))
    op.add_column('analyses', sa.Column('bowling_style', sa.String(length=50), nullable=True))
    op.add_column('analyses', sa.Column('release_height', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('release_speed', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('accuracy_score', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('violations', sa.JSON(), nullable=True))
    op.add_column('analyses', sa.Column('head_stillness', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('shot_selection', sa.String(length=100), nullable=True))
    op.add_column('analyses', sa.Column('recommendations', sa.JSON(), nullable=True))
    op.add_column('analyses', sa.Column('pose_data', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('analyses_session_id_key'), 'analyses', type_='unique')
    op.add_column('deliveries', sa.Column('shoulder_angle', sa.Float(), nullable=True))
    op.add_column('deliveries', sa.Column('release_frame', sa.Integer(), nullable=True))
    op.add_column('deliveries', sa.Column('pitch_frame', sa.Integer(), nullable=True))
    op.add_column('deliveries', sa.Column('is_no_ball', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'is_no_ball')
    op.drop_column('deliveries', 'pitch_frame')
    op.drop_column('deliveries', 'release_frame')
    op.drop_column('deliveries', 'shoulder_angle')
    op.create_unique_constraint(op.f('analyses_session_id_key'), 'analyses', ['session_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('analyses', 'pose_data')
    op.drop_column('analyses', 'recommendations')
    op.drop_column('analyses', 'shot_selection')
    op.drop_column('analyses', 'head_stillness')
    op.drop_column('analyses', 'violations')
    op.drop_column('analyses', 'accuracy_score')
    op.drop_column('analyses', 'release_speed')
    op.drop_column('analyses', 'release_height')
    op.drop_column('analyses', 'bowling_style')
    op.drop_column('analyses', 'bowling_arm')
    # ### end Alembic commands ###
