"""add_source_url_to_videos

Revision ID: 94e87ece3f35
Revises: ba2d393b9768
Create Date: 2026-04-29 10:43:50.603717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e87ece3f35'
down_revision: Union[str, Sequence[str], None] = 'ba2d393b9768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('source_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'source_type')
    op.drop_column('videos', 'source_url')
    # ### end Alembic commands ###
